### Zero e Identidade

In [10]:
import numpy as np
print('np.zeros([3, 3]):')
print(np.zeros([3, 3]))

np.zeros([3, 3]):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
#Matriz identidade é aquela matriz quadrada que possui 1's na diagonal principal e 0's ao redor
print('np.identity(3):')
print(np.identity(3))

np.identity(3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Matrix addition

In [3]:
#Só é possivel somar matrizes com o msm numero de linhas e colunas
A = np.array([[ 1, 4, 0],
              [-2, 6, 5]])
O = np.zeros([2, 3])

print('A:')
print(A)
print()
print('A + O:')
print(A + O)
print()
print('O + A:')
print(O + A)

A:
[[ 1  4  0]
 [-2  6  5]]

A + O:
[[ 1.  4.  0.]
 [-2.  6.  5.]]

O + A:
[[ 1.  4.  0.]
 [-2.  6.  5.]]


In [4]:
A = np.array([[ 1, 4, 0],
              [-2, 6, 5]])
B = np.array([[-3, 1, -1],
              [3, 0, 2]])

print('A:')
print(A)
print()
print('B:')
print(B)
print()
print('A + B:')
print(A + B)
print()
print('B + A:')
print(B + A)

A:
[[ 1  4  0]
 [-2  6  5]]

B:
[[-3  1 -1]
 [ 3  0  2]]

A + B:
[[-2  5 -1]
 [ 1  6  7]]

B + A:
[[-2  5 -1]
 [ 1  6  7]]


### Multiplicação escalar

In [5]:
A = np.array([[ 1, 4, 0],
              [-2, 6, 5]])

print('A:')
print(A)
print()
print('2*A:')
print(2*A)

A:
[[ 1  4  0]
 [-2  6  5]]

2*A:
[[ 2  8  0]
 [-4 12 10]]


# Multiplicação de matrizes

In [6]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
I = np.identity(3)

print('A:')
print(A)
print()
print('A@I:')
print(A@I)
print()
print('I@A:')
print(I@A)

A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

A@I:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

I@A:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [7]:
F = np.array([[6, 3, 10],
              [4, 8,  5]])
P = np.array([[0.10, 0.15],
              [0.40, 0.30],
              [0.10, 0.20]])

print('Quant. frutas F:')
print(F)
print()
print('Preços P:')
print(P)
print()
print('Custo total FS:')
print(F@P)

Quant. frutas F:
[[ 6  3 10]
 [ 4  8  5]]

Preços P:
[[0.1  0.15]
 [0.4  0.3 ]
 [0.1  0.2 ]]

Custo total FS:
[[2.8 3.8]
 [4.1 4. ]]


In [8]:
print(F.dot(P))

[[2.8 3.8]
 [4.1 4. ]]


### Matriz inversa

In [9]:
from numpy.linalg import inv
%precision 3

H = np.array([[1/(i + j - 1) 
                for j in range(1, 6)] 
                    for i in range(1, 6)])

print('H =')
print(H)
print()
print('inv(H) =')
print(inv(H))
print()
print('H@inv(H) =')
print(H@inv(H))
print()
print('inv(H)@H =')
print(inv(H)@H)
print()
print('inv(inv(H)) =')
print(inv(inv(H)))

H =
[[1.    0.5   0.333 0.25  0.2  ]
 [0.5   0.333 0.25  0.2   0.167]
 [0.333 0.25  0.2   0.167 0.143]
 [0.25  0.2   0.167 0.143 0.125]
 [0.2   0.167 0.143 0.125 0.111]]

inv(H) =
[[ 2.500e+01 -3.000e+02  1.050e+03 -1.400e+03  6.300e+02]
 [-3.000e+02  4.800e+03 -1.890e+04  2.688e+04 -1.260e+04]
 [ 1.050e+03 -1.890e+04  7.938e+04 -1.176e+05  5.670e+04]
 [-1.400e+03  2.688e+04 -1.176e+05  1.792e+05 -8.820e+04]
 [ 6.300e+02 -1.260e+04  5.670e+04 -8.820e+04  4.410e+04]]

H@inv(H) =
[[ 1.000e+00 -5.037e-13  1.357e-12  4.760e-13 -2.380e-13]
 [ 1.312e-14  1.000e+00 -5.246e-13 -1.003e-12 -7.112e-13]
 [ 1.531e-14 -2.899e-13  1.000e+00  1.219e-12  4.298e-13]
 [ 0.000e+00 -2.274e-13  0.000e+00  1.000e+00  0.000e+00]
 [-7.278e-16  2.719e-14 -3.497e-13  1.150e-12  1.000e+00]]

inv(H)@H =
[[ 1.000e+00 -1.764e-13 -1.187e-13 -9.948e-14 -8.441e-14]
 [ 4.058e-13  1.000e+00  3.598e-13  4.547e-13  3.304e-13]
 [-4.464e-12 -3.556e-12  1.000e+00 -9.095e-13 -1.158e-12]
 [ 2.659e-12  1.422e-12  6.994e-13  1.00

Veteroes numpy

In [ ]:
import numpy as np
u = np.array ([3, 2])
print(f'u    ={u}')
v = np.array ([1, -1])
print(f' u+v = {2*v}')

In [ ]:
#Combinação linear
v1 = np.array([1, 0, -1])
v2 = np.array([2, -3, 1])
v3 = np.array([5, -4, 0])
print(f'v1 = {v1}')
print(f'v2 = {v2}')
print(f'v3 = {v3}')
print()
print(f'')

In [7]:
#Produto escalar
#dot faz multiplicação de matrizes
u = np.array([ 1, 2, -3])
v = np.array([-3, 5, 2])
print(f'u = {u}')
print(f'v = {v}')
print(f'u.dot(v) = {u.dot(v)}')
print(f'u@v = {u@v}')

u = [ 1  2 -3]
v = [-3  5  2]
u.dot(v) = 1
u@v = 1


In [8]:
#Norma ou módulo
from numpy.linalg import norm
v = np.array([2, -1, 3])
print(f'v = {v}')
print(f'norma(v) = {norm(v)}')


v = [ 2 -1  3]
norma(v) = 3.7416573867739413


In [9]:
#Normalização de vetores(encontrar um vetor unitario = 1)
V = np.array([2, -1, 3])
u = (1/norm(v))*v
print(f'v = {v}')
print(f' u = {u}')
print(f'norm(u) = {norm(u)}')


v = [ 2 -1  3]
 u = [ 0.53452248 -0.26726124  0.80178373]
norm(u) = 1.0
